const events = [
    {
        category: "Agricultural and Food Security",
        location: "Ashkelon, Israel",
        address: "123 Main Street, Ashkelon",
        title: "Help in School Construction",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2013-03-10T02:00:00Z",
        endDate: "2013-03-10T04:00:00Z",
        capacity: 20,
        description: "Join us to build an educational future",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Agricultural and Food Security",
        location: "Afula, Israel",
        address: "456 Oak Avenue, Afula",
        title: "Reforestation Campaign",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2013-03-10T02:00:00Z",
        endDate: "2013-03-10T04:00:00Z",
        capacity: 15,
        description: "Contribute to the environment by planting trees.",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Community Service",
        location: "Tel Aviv, Israel",
        address: "7 Main Street, Tel Aviv",
        title: "Neighborhood Cleanup",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2023-05-15T02:00:00Z",
        endDate: "2023-05-17T04:00:00Z",
        capacity: 10,
        description: "Join us in keeping our community clean and beautiful. We'll be picking up litter and beautifying public spaces.",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Community Service",
        location: "Ashkelon, Israel",
        address: "14 Oak Avenue, Ashkelon",
        title: "Soup Kitchen Assistance",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2023-06-01T02:00:00Z",
        endDate: "2023-06-05T04:00:00Z",
        capacity: 10,
        description: "Volunteer at the local soup kitchen to help provide warm meals to those in need.",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Education and Tutoring",
        location: "Rishon Letsiyon, Israel",
        address: "XX School, Rishon Letsiyon",
        title: "After-School Tutoring",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2023-06-10T02:00:00Z",
        endDate: "2023-06-25T04:00:00Z",
        capacity: 5,
        description: "Assist students with their homework and provide extra support in various subjects.",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Education and Tutoring",
        location: "Jerusalem, Israel",
        address: "City Library, Jerusalem",
        title: "Literacy Workshop",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2023-06-10T02:00:00Z",
        endDate: "2023-06-25T04:00:00Z",
        capacity: 5,
        description: "Help organize a literacy workshop to promote reading and writing skills among children.",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Health and Wellness",
        location: "Jerusalem, Israel",
        address: "Community Center, Jerusalem",
        title: "Blood Drive",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2023-05-25T02:00:00Z",
        endDate: "2023-06-10T04:00:00Z",
        capacity: 5,
        description: "Donate blood and save lives. Every donation makes a difference.",
        languages: ["English", "Hebrew"],
    },
    {
        category: "Health and Wellness",
        location: "Tel Aviv, Israel",
        address: "City Hospital, Tel Aviv",
        title: "Hospital Volunteer Day",
        imageUrl: "https://source.unsplash.com/random?volunteering",
        startDate: "2023-05-25T02:00:00Z",
        endDate: "2023-06-10T04:00:00Z",
        capacity: 5,
        description: "Volunteer at the hospital to support healthcare professionals and bring comfort to patients.",
        languages: ["English", "Hebrew"],
    },
]

export default events;